I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 27, in script call
    call QUESTION
  File "game/script.rpy", line 105, in script
    python:
  File "game/script.rpy", line 119, in <module>
    question = json.loads(requests.get(BASE_URL+'getQuestion').text)
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 27, in script call
    call QUESTION
  File "game/script.rpy", line 105, in script
    python:
  File "/Users/data_machine/Desktop/ECS 289G Project/renpy-8.0.3-sdk/renpy/ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Users/data_machine/Desktop/ECS 289G Project/renpy-8.0.3-sdk/renpy/python.py", line 1061, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 119, in <module>
    question = json.loads(requests.get(BASE_URL+'getQuestion').text)
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/json/__init__.py", line 346, in loads
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/json/decoder.py", line 337, in decode
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/json/decoder.py", line 355, in raw_decode
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

macOS-10.16-x86_64-i386-64bit x86_64
Ren'Py 8.0.3.22090809
recursionrenpy 1.0
Sun Mar 19 10:26:47 2023
